### ISSUE TITLE
Github GPG service is offline

### ISSUE THREAD

**Issue by bjgwak** [KAIST-IS521/Agreement#47]
![default](https://cloud.githubusercontent.com/assets/19285069/24862871/707de456-1e39-11e7-8975-b368e566525e.PNG)

우선 많이 늦어져서 죄송합니다. 
GPG key를 업로드하려고 하는데 현재 위 메시지처럼 현재 서버가 오프라인 상태이므로 나중에 시도하라는 메시지가 나옵니다. 제가 혹시 놓친 게 있나요?

**Comment by sangkilc** [comment]
나중에 시도해봐야할 것 같습니다. 깃 허브에 일시적인 문제가 있는 것으로 보입니다.
